server:
  port: 8080
web:
  upload-path: e:/dt/head/
  front-path: e:/dt/image  
spring:

    datasource:
        name: localhost
        url: jdbc:mysql://localhost:3306/zhuding?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: root

        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    resources:
         static-locations: file:${web.upload-path},file:${web.front-path}
    
    redis:
      host: 127.0.0.1  
      port: 6379
      password: requirepass
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
      timeout: 0
       
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappering/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.foreseers.tj.model  # 注意：对应实体类的路径com.example.demo.model
 # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImp

  
#返回的前缀   目录对应src/main/webapp下
#spring.mvc.view.prefix: /WEB-INF/jsp/
#返回的后缀
#spring.mvc.view.suffix: .jsp

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  file: zhuding.log    
  level:
    com.foreseers.tj.mapper : debug




