server:
  port: 443    #8080  443
  ssl:
     key-store: foreseers_cn.p12         #tomcat.key  foreseers_cn.p12
     key-store-type: JKS
     key-alias: tomcat
     key-store-password: foreseers  #testhttps  foreseers
  tomcat:
   max-http-post-size: 8192
      
    
web:
  upload-path: /var/zhuding/head/  #头像地址  /var/zhuding/head/  e:/dt/head/
  front-path: /var/zhuding/image/  #相册地址/var/zhuding/image/   e:/dt/image/
 
httpurl: https://chat.foreseers.cn:443/   #图片保存到数据库的url地址  https://chat.foreseers.cn:443/
#httpurl: http://192.168.1.73:8080/   #图片保存到数据库的url地址  https://chat.foreseers.cn:443/

spring:
    datasource:
        name: localhost
        url: jdbc:mysql://localhost:3306/zhuding?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: lover      
        password: forDating  

        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    resources:
         static-locations: file:${web.upload-path},file:${web.front-path},classpath:/static/

       
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappering/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.foreseers.tj.model  # 注意：对应实体类的路径com.example.demo.model
 # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImp

  
#返回的前缀   目录对应src/main/webapp下
#spring.mvc.view.prefix: /WEB-INF/jsp/
#返回的后缀
#spring.mvc.view.suffix: .jsp

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  file: zhuding.log    
  level: 
    com.foreseers.tj.mapper : debug
    com.foreseers.tj.service.impl : debug




